config/routes.rb
TimeSheet::Application.routes.draw do
  
  
  

  resources :projects

  resources :settings

  match '/contact', :to => "pages#contact"
  match '/about', :to => "pages#about"
  match '/works/all', :to => "works#all_work" 
  match '/api/create', :to => "api#create", :via => :post
  match '/api/send_message', :to => "api#send_message"
  match '/projects/:project_id/story/:story_id', :to => "projects#story", :as => :project_story
  match '/pt-api', :to => "pt_api#index", :via => :post
  match '/api/log-time/:activity_id/:time', :to => "api#log_time"
  match '/api/log-custom-time/:activity_id', :to => "api#log_custom_time"
  match '/projects/:project_id/overview', :to => "projects#overview", :as => :project_overview  

  
  resources :works
  devise_for :users
  
  match 'activity' => 'activity#index'

  root :to => 'pages#home'  

end

app/models/work.rb
# == Schema Information
# Schema version: 20111220151843
#
# Table name: works
#
#  id          :integer(4)      not null, primary key
#  day         :date
#  description :string(255)
#  time        :integer(4)
#  created_at  :datetime
#  updated_at  :datetime
#  user_id     :integer(4)      not null
#  task_id     :integer(4)      not null
#

class Work < ActiveRecord::Base
  belongs_to :user
  
  validates :day, :presence => true
  validates :time, :presence =>true
  validates :description,  :presence => true,
                            :length   => { :maximum => 255 }
  validates :user_id, :presence => true 
  
  validates_format_of :day, :with => /\d{4}\-\d{2}\-\d{2}/, :message => "Date must be in the following format: yyyy-mm-dd"
  validates_numericality_of :time, :integer_only => true, :greater_than => 0  
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :admin?, :only => [:all_work]
  before_filter :find_work, :only => [:show, :edit, :update, :destroy]
  before_filter :set_title
  
  # GET /works
  # GET /works.xml
  def index
   
    if !params["date"]
      @month = Time.now.month
      @year  = Time.now.year
    else
      date = params["date"]
      @month = date["month"].to_i
      @year = date["year"].to_i
    end
    @day = Date.new(@year,@month,1)
    @days = (@day.beginning_of_month..@day.end_of_month ).to_a
    
    @works = current_user.works.order('day DESC')
    @works = @works.group_by(&:day)
     
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @works }
    end
  end

  # GET /works/1
  # GET /works/1.xml
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @work }
      format.json { render :json => @work}
      format.pdf do
        pdf = PDF::Writer.new
        pdf.text "test"
        send_data pdf.render, :filename => 'works.pdf', :type => 'application/pdf', :disposition => 'inline'
      end
    end
  end

  # GET /works/new
  # GET /works/new.xml
  def new
    @title = "New work"
     @attr = { 
        :day => Date.today.to_s() , 
        :description => "", 
        :time => nil,
        :user_id => nil 
      }
    
    
    if params["day"]
      @attr = @attr.merge(:day => params["day"])
    end
    @work = Work.new(@attr)

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @work }
    end
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.xml
  def create
    @work = current_user.works.build(params[:work])

    respond_to do |format|
      if @work.save
        format.html { redirect_to(@work, :notice => 'Work was successfully created.') }
        format.xml  { render :xml => @work, :status => :created, :location => @work }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @work.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /works/1
  # PUT /works/1.xml
  def update
    respond_to do |format|
      if @work.update_attributes(params[:work])
        format.html { redirect_to(@work, :notice => 'Work was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @work.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.xml
  def destroy
    @work.destroy

    respond_to do |format|
      format.html { redirect_to(works_url) }
      format.xml  { head :ok }
    end
  end
  
  def all_work
    @works = Work.all
  end
  
  def download
  
  end
  
  private
  
    def find_work
      @work = current_user.works.find(params[:id])
    end
    
    def current_user_work(start_day,stop_day)
      @work = current_user.works.find(:all, :conditions => [ "day >= ? AND day <= ?", start_day, stop_day], :order => "day")
    end
    
    
    def fill_ext_work
      if current_user.settings.where('settings.name' => 'Pivotal Tracker').first.enabled
        PivotalTracker::Client.token = current_user.settings.where('settings.name' => 'Pivotal Tracker').first.setting_value
        @project = PivotalTracker::Project.find(242503)
        #pivotal tracker
        @activity = @project.activities.all
        @today_activity =  @activity.select {|a| a.occurred_at > @work.day}
        if @today_activity.nil?
          @work.description = "Nil"
        else
          @description = ""
          @today_activity.each {|activity| @description += activity.description + "\n"}
          @work.description = @description.to_s()
        end
      end
      
    end
    
    def admin?
      if !current_user.admin?
       redirect_to root_path, :notice => "Please sign in as admin to access this page."
      end
    end
    
    def set_title
      @title = "Work"
    end
end

app/helpers/works_helper.rb
module WorksHelper
  def format_time(time_in_minutes)
    p time_in_minutes
    minutes = time_in_minutes % 60
    hours = time_in_minutes / 60
    format("%02d:%02d", hours, minutes) #=> "01:00"
  end
  
  def day_time(works)

  end
end

app/views/works/_ext_work.html.erb
<%= @externalwork %>

app/views/works/_form.html.erb
<%= form_for @work, :html => { :class => "form-horizontal"} do |f| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <% if @work.project_id && @work.story_id %>
    <% project_id = @work.project_id %>
    <% story_id = @work.story_id%>
  <% else %>
    <% project_id = params[:project_id] %>
    <% story_id = params[:story_id] %>
  <% end%>
  
  
  
  <fieldset>
    <legend>New work</legend>
    <div class="control-group">
      <%= f.label :day, :class => "control-label", :for =>"day_inputs" %>
      <div class="controls">
        <%= f.date_select :day, :id => "day_inputs" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :description, :readonly => true, :class => "control-label", :for =>"description_input" %>
      <div class="controls">
        <%= f.text_area :description, :cols => 20, :rows => 5, :id => "description_input", :value => params[:description] %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :time, :class => "control-label", :for =>"time_input" %>
      <div class="controls">
        <div class="input-append">
          <%= f.text_field :time, :id => "time_input", :class => "span2" %>
          <span class="add-on">minutes</span>
        </div>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :project_id, :class => "control-label", :for =>"project_id_input" %>
      <div class="controls">
        <%= f.text_field :project_id, :id => "project_id_input", :value => project_id %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :story_id, :class => "control-label", :for =>"story_id_input" %>
      <div class="controls">
        <%= f.text_field :story_id, :id => "story_id_input", :value => story_id %>
      </div>
    </div>
    <div class="form-actions">
       <%= f.submit :class => "btn btn-success"%>
    </div>
  </fieldset>
<% end %>

app/views/works/_load.html.erb
<%= link_to "Load", activity_path, :remote => true%>

app/views/works/_table.html.erb
# encoding: utf-8
<p>Task works</p>
<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>Description</th>
      <th>User</th>
      <th>Time</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @works.each do |work| %>
    <tr>
      <td><%= work.day %></td>
      <td><%= link_to work.description, work %></td>
      <td><%= work.user.email %></td>
      <td><%= work.time %></td>
      <td><%= link_to 'Edit', edit_work_path(work) %></td>
      <td><%= link_to 'Destroy', work, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <th>Celkem</th>
      <th></th>
      <th></th>
      <th><%= @works.sum :time %></th>
      <th></th>
      <th></th>
    </tr>
  </tfood>
</table>

app/views/works/_work.html.erb
<tr class="work">
  <td >
    <%= work.workday %>
  </td>
  <td>
	<%= work.activity %>
  </td> 
  <td>
	<%= work.worktime %>
  </td>
</tr>

app/views/works/all_work.html.erb
<h1>Listing works</h1>

<table>
  <tr>
    <th>Day</th>
    <th>Description</th>
    <th>Time</th>
	<th>User Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @works.each do |work| %>
  <tr>
    <td><%= work.day %></td>
    <td><%= work.description %></td>
    <td><%= work.time %></td>
    <td><%= work.user.email %></td>
    <td><%= link_to 'Show', work %></td>
    <td><%= link_to 'Edit', edit_work_path(work) %></td>
    <td><%= link_to 'Destroy', work, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Work', new_work_path %>

app/views/works/edit.html.erb
<h1>Editing work</h1>

<%= render 'form' %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/index.html.erb
<div class="row">
  <div class="span8"><h1>Work list</h1></div>
  <div class="span2">
    <a href="/works.pdf" class="btn btn-primary">
      <i class="icon-download-alt icon-white"></i>Download
    </a>
  </div>
</div>


<table class="table table-striped">
  <tr>
    <th>Day</th>
    <th>Story ID / Activity</th>
    <th>Time</th>
    <th></th>
  </th>
  <% @works.each do |day, day_works| %>   
    <tr>
      <td><%= day %></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <% day_works.each do |work|%>
    <tr>
      <td></td>
      <td>
      <% if work.project_id && work.story_id %>
        <%= link_to work.story_id, project_story_path(work.project_id, work.story_id) %> / <%= work.description %>
      <% else %>
        <%= work.description %>
      <% end %>
      </td>
      <td><%= format_time(work.time) %></td>
      <td><%= link_to "Edit", edit_work_path(work.id) %></td>
    </tr>
    <% end %>
    <tr>
      <th>Time summary:</th>
      <th></th>
      <th><%= format_time(day_works.sum(&:time)) %></th>
      <th></th>
    </tr>
  <% end%>
</table>

app/views/works/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', works_path %>

app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Day:</b>
  <%= @work.day %>
</p>

<p>
  <b>Description:</b>
  <%= @work.description %>
</p>

<p>
  <b>Time:</b>
  <%= @work.time %>
</p>


<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>