config/routes.rb
TimeSheet::Application.routes.draw do
  
  
  

  resources :projects

  resources :settings

  match '/contact', :to => "pages#contact"
  match '/about', :to => "pages#about"
  match '/works/all', :to => "works#all_work" 
  match '/api/create', :to => "api#create", :via => :post
  match '/api/send_message', :to => "api#send_message"
  match '/projects/:project_id/story/:story_id', :to => "projects#story", :as => :project_story
  match '/pt-api', :to => "pt_api#index", :via => :post
  match '/api/log-time/:activity_id/:time', :to => "api#log_time"
  match '/api/log-custom-time/:activity_id', :to => "api#log_custom_time"
  match '/projects/:project_id/overview', :to => "projects#overview", :as => :project_overview  

  
  resources :works
  devise_for :users
  
  match 'activity' => 'activity#index'

  root :to => 'pages#home'  

end

app/models/setting.rb
# == Schema Information
# Schema version: 20111220151843
#
# Table name: settings
#
#  id         :integer(4)      not null, primary key
#  name       :string(255)
#  APIkey     :string(255)
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer(4)      not null
#  enabled    :boolean(1)
#

class Setting < ActiveRecord::Base
  belongs_to :user
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  # GET /settings
  # GET /settings.xml
  
  
  before_filter :authenticate_user!
  before_filter :find_settings, :only => [:edit, :update]
  before_filter :set_title
  
  def index
    @setting = current_user.setting
    if @setting.nil? 
      redirect_to new_setting_path
      return
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @setting }
    end
  end
  
  def show
    redirect_to settings_path
  end

  # GET /settings/new
  # GET /settings/new.xml
  def new
    @setting = Setting.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @setting }
    end
  end

  # GET /settings/1/edit
  def edit

  end

  # POST /settings
  # POST /settings.xml
  def create
    @setting = current_user.build_setting(params[:setting])

    respond_to do |format|
      if @setting.save
        format.html { redirect_to(@setting, :notice => 'Setting was successfully created.') }
        format.xml  { render :xml => @setting, :status => :created, :location => @setting }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @setting.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /settings/1
  # PUT /settings/1.xml
  def update
    respond_to do |format|
      if @setting.update_attributes(params[:setting])
        format.html { redirect_to(@setting, :notice => 'Setting was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @setting.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  
  private
    def find_settings
      @setting = current_user.setting
    end
    
    def set_title
      @title = "Settings"
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_for(@setting) do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pt_api_key %><br />
    <%= f.text_field :pt_api_key %>
  </div>
  <div class="field">
    <%= f.label :pt_name %><br />
    <%= f.text_field :pt_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/settings/_form_disabled.html.erb
<%= form_for(@setting, :html => { :class => "form-horizontal" }) do |f| %>
<!--  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
-->
 <fieldset>
   <legend>Your Pivotal Tracker setting is on Profile page</legend>
   <div class="control-group">
     <%= f.label :pt_name, :class => "control-label", :for =>"pt_name_input" %>
     <div class="controls">
        <%= f.text_field :pt_name, :disabled => true, :class => "input-xlarge disabled", :id => "pt_name_input" %>
     </div>
   </div>
  <div class="control-group">
    <%= f.label :pt_api_key, :class => "control-label", :for =>"pt_api_key_input" %>
    <div class="controls">
       <%= f.text_field :pt_api_key, :disabled => true, :class => "input-xlarge disabled", :id => "pt_api_key_input" %>
    </div>
  </div>
  </fieldset>
<% end %>

app/views/settings/edit.html.erb
<h1>Edit Pivotal Tracker settings</h1>

<%= render 'form' %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<h1>Your settings</h1>
<div class="row">
  <div class="span4 offset8">
    <%= link_to 'Edit', edit_setting_path(@setting), :class => "btn btn-primary" %>
  </div>
</div>
<%= render 'form_disabled' %>

app/views/settings/new.html.erb
<h1>New setting</h1>

<%= render 'form' %>

<%= link_to 'Back', settings_path %>