config/routes.rb
TimeSheet::Application.routes.draw do
  
  
  

  resources :projects

  resources :settings

  match '/contact', :to => "pages#contact"
  match '/about', :to => "pages#about"
  match '/works/all', :to => "works#all_work" 
  match '/api/create', :to => "api#create", :via => :post
  match '/api/send_message', :to => "api#send_message"
  match '/projects/:project_id/story/:story_id', :to => "projects#story", :as => :project_story
  match '/pt-api', :to => "pt_api#index", :via => :post
  match '/api/log-time/:activity_id/:time', :to => "api#log_time"
  match '/api/log-custom-time/:activity_id', :to => "api#log_custom_time"
  match '/projects/:project_id/overview', :to => "projects#overview", :as => :project_overview  

  
  resources :works
  devise_for :users
  
  match 'activity' => 'activity#index'

  root :to => 'pages#home'  

end

app/controllers/projects_controller.rb
# encoding: utf-8
class ProjectsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :set_title
  # GET /projects
  # GET /projects.xml
  def index
    #@projects = Project.all
    PivotalTracker::Client.token = current_user.setting.pt_api_key
    logger.debug current_user.setting.pt_api_key
    @projects = PivotalTracker::Project.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show    
    PivotalTracker::Client.token = current_user.setting.pt_api_key
    @project = PivotalTracker::Project.find(params[:id].to_i)
    @stories = @project.stories.all

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
  
  def story
    PivotalTracker::Client.token = current_user.setting.pt_api_key
    @project = PivotalTracker::Project.find(params[:project_id].to_i)
    @story = @project.stories.find(params[:story_id].to_i)
    @works = Work.where("project_id >= :project_id AND story_id <= :story_id", {:project_id => params[:project_id], :story_id => params[:story_id].to_i})
    @story_time = @works.map(&:time).inject(:+)
         
    respond_to do |format|
      format.html { render :action => "story" }
      format.xml  { head :ok }
    end
  end
  
  def overview
    PivotalTracker::Client.token = current_user.setting.pt_api_key
    @project = PivotalTracker::Project.find(params[:project_id].to_i)
    owner_email = @project.memberships.all.select{|x| x.role == "Owner"}.first.email
    @h ={}
    if current_user.email == owner_email
      @users = User.all
      @project.memberships.all.select{|x| x.role == "Owner"}
      @users.each do |user|
        works = Work.where(:project_id => params[:project_id], :user_id => user.id)
        time = works.present? ? works.sum(:time) : 0
        @h[user.email] = time
      end
    else 
      @users = [User.find(current_user.id)]
      works = Work.where(:project_id => params[:project_id], :user_id => current_user.id)
      time = works.present? ? works.sum(:time) : 0
      p time
      @h[current_user.email] = time
    end
    
    
     
  end
  
  private
    def set_title
      @title = "Projects"
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.text_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_story_table.html.erb
<p>Project tasks</p>
<table class="table table-striped">
  <tr>
    <th>Story ID</th>
    <th>State</th>
    <th>Name</th>
    <th>Hours</th>
  </tr>



<% @stories.each do |story| %>
  <tr>
    <td><%= link_to story.id, project_story_path(@project.id, story.id) %></td>
    <td><%= story.story_type %></td>
    <td><%= story.name %></td>
    <td></td>
  </tr>
<% end %>
</table>

app/views/projects/_users_work.html.erb
<h1>Users</h1>
<table class="table table-striped">
  <tr>
    <th>User</th>
    <th>Time</th>
  </tr>
  
<% @users.each do |user| %>
  <tr>
    <td><%= user.email.to_s %></td>
    <td><%= format_time(@h[user.email.to_s]) %></td>
  </tr>
<% end %>
</table>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table class="table table-striped">
  <tr>
    <th>Project name</th>
    <th>Actions</th>
  </tr>
  

<% @projects.each do |project| %>

<tr>
  <td><%= link_to project.name, project_path(project.id) %></td>
  <td><%= link_to "Overview", project_overview_path(project.id), :class => "btn btn-primary btn-mini"%></td>
</tr>


<% end %>
</table>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/overview.html.erb
<div class="row-fluid">
  <div class="span4">
    <%= link_to projects_path, :class => "btn btn-primary" do %>   
        <i class="icon-arrow-left icon-white"></i>
        Back to Projects
    <% end %>
  </div>
  <div class="span4">
    <h1><%= @project.id %> - <%= @project.name %>
  </div>
</div>

<%= render 'users_work' %>

app/views/projects/show.html.erb
<div class="row-fluid">
  <div class="span4">
    <%= link_to projects_path, :class => "btn btn-primary" do %>   
        <i class="icon-arrow-left icon-white"></i>
        Back to Projects
    <% end %>
  </div>
  <div class="span4">
    <h1><%= @project_id %> - <%= @project.name %>
  </div>
</div>

<%= render 'story_table' %>

app/views/projects/story.html.erb
<div class="row-fluid">
  <div class="span2">
    <%= link_to projects_path, :class => "btn btn-primary" do %>   
        <i class="icon-arrow-left icon-white"></i>
        Back to Projects
    <% end %>
  </div>
</div>
<div class="row-fluid">
&nbsp
<div>
  
<div class="row-fluid">
  <div class="span10">
    <h1><%= @project.name %> / <%= @story.name %></h1>  
  </div>
<div>
  
<div class="row-fluid">
&nbsp
<div>

<div class="row-fluid">
  <div class="span2">
      <%= @story.story_type %>
  </div>
  <div class="span8">
    <div class="row-fluid">
      <h3>Story description</h3>
    </div>
    <div class="row-fluid">
      <blockquote>
        <%= @story.description%>
      </blockquote>
    </div>
  </div>
</div>
<%= link_to "Add work", {:controller => "works", :action => "new", :story_id => @story.id, :project_id => @project.id }, html_options = {:class => "btn btn-success"} %>

<h2>Activities</h2>

<table class="table table-striped">
  <tr>
    <th>Day</th>
    <th>Activity</th>
    <th>Time</th>
    <th></th>
  </th>
  <% @works.each do |work| %>   
    <tr>
      <td><%= work.day %></td>
      <td><%= work.description.to_s %></td>
      <td><%= format_time(work.time) %></td>
      <td><%= link_to "Edit", edit_work_path(work.id) %></td>
    </tr>
  <% end %>
  <tr>
    <th>Time summary:</th>
    <th></th>
    <th><%= format_time(@works.sum(:time)) %></th>
    <th></th>
  </tr>
</table>