config/routes.rb
TimeSheet::Application.routes.draw do
  
  
  

  resources :projects

  resources :settings

  match '/contact', :to => "pages#contact"
  match '/about', :to => "pages#about"
  match '/works/all', :to => "works#all_work" 
  match '/api/create', :to => "api#create", :via => :post
  match '/api/send_message', :to => "api#send_message"
  match '/projects/:project_id/story/:story_id', :to => "projects#story", :as => :project_story
  match '/pt-api', :to => "pt_api#index", :via => :post
  match '/api/log-time/:activity_id/:time', :to => "api#log_time"
  match '/api/log-custom-time/:activity_id', :to => "api#log_custom_time"
  match '/projects/:project_id/overview', :to => "projects#overview", :as => :project_overview  

  
  resources :works
  devise_for :users
  
  match 'activity' => 'activity#index'

  root :to => 'pages#home'  

end

app/views/layouts/_flash.html.erb
<div>
    <%- if !notice.nil? -%>
    <p><%= notice %></p>
    <%- end -%> 
    <%- if !alert.nil? -%>
    <p><%= alert %></p>
    <%- end -%>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Time Sheet version 2.0.1", root_path, :class => 'brand'%>
    	<div class="nav-collapse">
      	<ul class="nav">
      	  <%if @title.to_s == "Work" %>
            <li class = "active"><%= link_to "My Work", works_path%></li>
          <% else %>
            <li><%= link_to "My Work", works_path%></li>
          <%end%>
          <%if @title.to_s == "Projects" %>
            <li class = "active"><%= link_to "Projects", projects_path%></li>
          <% else %>
            <li><%= link_to "Projects", projects_path%></li>
          <%end%>
          <%if @title.to_s == "Settings" %>
            <li class = "active"><%= link_to "Settings", settings_path%></li>
          <% else %>
            <li><%= link_to "Settings", settings_path%></li>
          <%end%>
        </ul>
        <ul class="nav pull-right">
    			<%= render 'devise/menu/admin' %>
          <%= render 'devise/menu/registration_items' %>
    			<%= render 'devise/menu/login_items' %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= stylesheet_link_tag 'bootstrap.min', :media => 'screen' %>
<%= stylesheet_link_tag 'bootstrap-responsive.min'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag :defaults, 'jquery-1.7.2' %>
  <%= javascript_include_tag :defaults, 'bootstrap' %>
  <%= csrf_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		 <%= yield %>
	</div>
</body>
</html>